[project]
name = "casa-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dotenv>=0.9.9",
    "openai>=1.76.2",
    "openai-agents>=0.0.14",
    "prompt-toolkit>=3.0.51",
]
